org: dilshaniit
app: sleek-style
service: suggestion-selector
frameworkVersion: '3'

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-plugin-typescript
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1
  environment:
    S3_BUCKET_HAIRSTYLE_SUGGESTIONS: ${{ vars.S3_BUCKET_HAIRSTYLE_SUGGESTIONS }}
    S3_BUCKET_USER_DATA: ${{ vars.S3_BUCKET_USER_DATA }}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

  upload-user-image:
    handler: uploadUserImage.get
    events:
      - http:
          path: suggestion-selector/upload-user-image
          method: get
          cors: true
    iamRoleStatementsName: ${self:app}-${self:service}-upload-user-image
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "s3:PutObject"
          - "s3:GetObject"
        Resource: 
          Fn::Join: ["", [ "arn:aws:s3:::", "*/*" ]]