org: dilshaniit
app: sleek-style
service: hairstyle-recommender
frameworkVersion: '3'

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-plugin-typescript
  - serverless-iam-roles-per-function
  - serverless-openapi-documentation

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    S3_BUCKET_HAIRSTYLE_SUGGESTIONS: ${param:S3_BUCKET_HAIRSTYLE_SUGGESTIONS}
    S3_BUCKET_USER_DATA: ${param:S3_BUCKET_USER_DATA}
    DYNAMODB_TABLE_USER_DATA: ${param:DYNAMODB_TABLE_USER_DATA}

functions:
  save-user-data:
    handler: saveUserData.post
    events:
      - http:
          path: /save-user-data
          method: post
    iamRoleStatementsName: ${self:app}-${self:service}-save-user-data
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "s3:PutObject"
          - "s3:GetObject"
        Resource: 
          Fn::Join: ["", [ "arn:aws:s3:::", "${param:S3_BUCKET_USER_DATA}/*" ]]
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
        Resource: 
          Fn::Join: [ "", [ "arn:aws:dynamodb:", { Ref: "AWS::Region" }, ':', { Ref: "AWS::AccountId" }, ":table/${param:DYNAMODB_TABLE_USER_DATA}" ] ]
  
  get-hair-style-suggestions:
    handler: getHairStyleSuggestions.get
    events:
      - http:
          path: /get-hair-style-suggestions
          method: get
    iamRoleStatementsName: ${self:app}-${self:service}-get-hair-style-suggestions
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "s3:PutObject"
          - "s3:GetObject"
        Resource: 
          Fn::Join: ["", [ "arn:aws:s3:::", "${param:S3_BUCKET_USER_DATA}/*" ]]
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
          - dynamodb:GetItem
        Resource: 
          Fn::Join: [ "", [ "arn:aws:dynamodb:", { Ref: "AWS::Region" }, ':', { Ref: "AWS::AccountId" }, ":table/${param:DYNAMODB_TABLE_USER_DATA}" ] ]