org: dilshaniit
app: sleek-style
service: hairstyle-recommender
frameworkVersion: '3'

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-plugin-typescript
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    S3_BUCKET_HAIRSTYLE_SUGGESTIONS: ${param:S3_BUCKET_HAIRSTYLE_SUGGESTIONS}
    S3_BUCKET_USER_DATA: ${param:S3_BUCKET_USER_DATA}

functions:
  get-hairstyle-suggestions:
    handler: handler.get
    events:
      - http:
          path: /
          method: get

  upload-user-image:
    handler: uploadUserImage.get
    events:
      - http:
          path: suggestion-selector/upload-user-image
          method: put
          cors: true
    iamRoleStatementsName: ${self:app}-${self:service}-upload-user-image
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "s3:PutObject"
          - "s3:GetObject"
        Resource: 
          Fn::Join: ["", [ "arn:aws:s3:::", "${param:S3_BUCKET_USER_DATA}/*" ]]