name: Deploy hairstyle recommender prod

on:
  push:
    branches:
      - main
    paths:
      - 'hairstyle-recommender/**'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: Prod
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm cache clean --force
      working-directory: ./hairstyle-recommender
    - run: npm install
      working-directory: ./hairstyle-recommender
    - name: Serverless deploy hairstyle recommender
      uses: serverless/github-action@v3.1
      with:
        args: -c "cd ./hairstyle-recommender && sls deploy -s prod -r ap-southeast-1"
        entrypoint: /bin/sh
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}