name: Deploy suggestion selector prod

on:
  push:
    branches:
      - main
    paths:
      - 'suggestion-selector/**'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: Prod
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm cache clean --force
      working-directory: ./suggestion-selector
    - run: npm install
      working-directory: ./suggestion-selector
    - name: Serverless deploy suggestion selector
      uses: serverless/github-action@v3.1
      with:
        args: -c "cd ./suggestion-selector && serverless deploy -s prod -r ap-southeast-1"
        entrypoint: /bin/sh
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}